In [ ]:
# Data Overview and Understanding
This notebook explores the structure, size, and quality of the datasets provided. 
Objective: Understand data before performing any analysis/optimization.

In [10]:
import os
print("Current working directory:", os.getcwd())

Current working directory: C:\Users\Dell

In [23]:
#libraries
import pandas as pd
import numpy as np
import os
os.chdir(r"C:\Users\Dell\Desktop\inventory-optimization-project\notebooks")
print("New working directory:", os.getcwd())

New working directory: C:\Users\Dell\Desktop\inventory-optimization-project\notebooks

In [76]:
import os

print(os.listdir("../data/raw/"))

['begin_inventory.csv', 'end_inventory.csv', 'invoice_purchases.csv', 'price.csv', 'purchases.csv', 'sales.csv']

DATA_PATH = "../data/raw/"
sales_df = pd.read_csv(DATA_PATH + "sales.csv")

### sales Dataset – Observations
- This dataset contains transaction-level sales data across multiple stores.
- It includes sales quantity, sales value, pricing, store information, and product classification.
- The dataset is large in size, indicating high transaction volume and justifying the use of programmatic analysis.

In [33]:
sales_df.shape #no.of (rows, columns)

(1048575, 14)

In [34]:
sales_df.columns #(column names)

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='object')

In [35]:
sales_df.info() #

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 14 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   InventoryId     1048575 non-null  object
 1   Store           1048575 non-null  int64
 2   Brand           1048575 non-null  int64
 3   Description     1048575 non-null  object
 4   Size            1048575 non-null  object
 5   SalesQuantity   1048575 non-null  int64
 6   SalesDollars    1048575 non-null  float64
 7   SalesPrice      1048575 non-null  float64
 8   SalesDate       1048575 non-null  object
 9   Volume          1048575 non-null  int64
 10  Classification  1048575 non-null  int64
 11  ExciseTax       1048575 non-null  float64
 12  VendorNo        1048575 non-null  int64
 13  VendorName      1048575 non-null  object
dtypes: float64(3), int64(6), object(5)
memory usage: 112.0+ MB

In [36]:
sales_df.isna().sum() #missing value per column

InventoryId       0
Store             0
Brand             0
Description       0
Size              0
SalesQuantity     0
SalesDollars      0
SalesPrice        0
SalesDate         0
Volume            0
Classification    0
ExciseTax         0
VendorNo          0
VendorName        0
dtype: int64

In [37]:
sales_df.head() #first 5 rows

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,1/1/2016,750,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,1/2/2016,750,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,1/3/2016,750,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,1/8/2016,750,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,1/9/2016,375,1,0.79,12546,JIM BEAM BRANDS COMPANY

In [39]:
purchases_df = pd.read_csv(DATA_PATH + "purchases.csv")

In [41]:
purchases_df.shape

(2372474, 16)

In [42]:
purchases_df.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'VendorNumber',
       'VendorName', 'PONumber', 'PODate', 'ReceivingDate', 'InvoiceDate',
       'PayDate', 'PurchasePrice', 'Quantity', 'Dollars', 'Classification'],
      dtype='object')

In [43]:
purchases_df.info

<bound method DataFrame.info of                   InventoryId  Store  Brand                   Description  \
0           69_MOUNTMEND_8412     69   8412     Tequila Ocho Plata Fresno
1            30_CULCHETH_5255     30   5255  TGI Fridays Ultimte Mudslide
2           34_PITMERDEN_5215     34   5215  TGI Fridays Long Island Iced
3         1_HARDERSFIELD_5255      1   5255  TGI Fridays Ultimte Mudslide
4           76_DONCASTER_2034     76   2034     Glendalough Double Barrel
...                       ...    ...    ...                           ...
2372469     49_GARIGILL_22298     49  22298       Zorvino Vyds Sangiovese
2372470  1_HARDERSFIELD_19556      1  19556    Zorvino Bacca Z Blackberry
2372471   66_EANVERNESS_22297     66  22297            Zorvino Vyds Pearz
2372472    69_MOUNTMEND_19557     69  19557  Zorvino Fragole Z Strawberry
2372473    55_DRY GULCH_22298     55  22298       Zorvino Vyds Sangiovese

          Size  VendorNumber                   VendorName  PONumber  \
0        750mL           105  ALTAMAR BRANDS LLC               8124
1        1.75L          4466  AMERICAN VINTAGE BEVERAGE        8137
2        1.75L          4466  AMERICAN VINTAGE BEVERAGE        8137
3        1.75L          4466  AMERICAN VINTAGE BEVERAGE        8137
4        750mL           388  ATLANTIC IMPORTING COMPANY       8169
...        ...           ...                          ...       ...
2372469  750mL         90058  ZORVINO VINEYARDS               13593
2372470  750mL         90058  ZORVINO VINEYARDS               13593
2372471  750mL         90058  ZORVINO VINEYARDS               13593
2372472  750mL         90058  ZORVINO VINEYARDS               13593
2372473  750mL         90058  ZORVINO VINEYARDS               13593

             PODate ReceivingDate InvoiceDate     PayDate  PurchasePrice  \
0        2015-12-21    2016-01-02  2016-01-04  2016-02-16          35.71
1        2015-12-22    2016-01-01  2016-01-07  2016-02-21           9.35
2        2015-12-22    2016-01-02  2016-01-07  2016-02-21           9.41
3        2015-12-22    2016-01-01  2016-01-07  2016-02-21           9.35
4        2015-12-24    2016-01-02  2016-01-09  2016-02-16          21.32
...             ...           ...         ...         ...            ...
2372469  2016-12-19    2016-12-28  2017-01-09  2017-02-06           8.06
2372470  2016-12-19    2016-12-27  2017-01-09  2017-02-06           9.39
2372471  2016-12-19    2016-12-26  2017-01-09  2017-02-06           6.75
2372472  2016-12-19    2016-12-26  2017-01-09  2017-02-06           9.39
2372473  2016-12-19    2016-12-28  2017-01-09  2017-02-06           8.06

         Quantity  Dollars  Classification
0               6   214.26               1
1               4    37.40               1
2               5    47.05               1
3               6    56.10               1
4               5   106.60               1
...           ...      ...             ...
2372469        12    96.72               2
2372470        12   112.68               2
2372471        12    81.00               2
2372472        12   112.68               2
2372473        12    96.72               2

[2372474 rows x 16 columns]>

In [44]:
purchases_df.isna().sum()

InventoryId       0
Store             0
Brand             0
Description       0
Size              3
VendorNumber      0
VendorName        0
PONumber          0
PODate            0
ReceivingDate     0
InvoiceDate       0
PayDate           0
PurchasePrice     0
Quantity          0
Dollars           0
Classification    0
dtype: int64

In [75]:
purchases_df.head()

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2015-12-21,2016-01-02,2016-01-04,2016-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2015-12-22,2016-01-01,2016-01-07,2016-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2015-12-22,2016-01-02,2016-01-07,2016-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2015-12-22,2016-01-01,2016-01-07,2016-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2015-12-24,2016-01-02,2016-01-09,2016-02-16,21.32,5,106.60,1

In [45]:
invoice_df = pd.read_csv(DATA_PATH + "invoice_purchases.csv")

In [46]:
invoice_df.shape

(12261, 9)

In [47]:
invoice_df.columns

Index(['Brand', 'Description', 'Price', 'Size', 'Volume', 'Classification',
       'PurchasePrice', 'VendorNumber', 'VendorName'],
      dtype='object')

In [49]:
invoice_df.isna().sum()

Brand             0
Description       1
Price             0
Size              1
Volume            1
Classification    0
PurchasePrice     0
VendorNumber      0
VendorName        0
dtype: int64

In [74]:
invoice_df.head()

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

In [50]:
begin_inv_df = pd.read_csv(DATA_PATH + "begin_inventory.csv")

In [53]:
begin_inv_df.shape

(206529, 9)

In [56]:
begin_inv_df.isna().sum()

InventoryId    0
Store          0
City           0
Brand          0
Description    0
Size           0
onHand         0
Price          0
startDate      0
dtype: int64

In [55]:
begin_inv_df.columns

Index(['InventoryId', 'Store', 'City', 'Brand', 'Description', 'Size',
       'onHand', 'Price', 'startDate'],
      dtype='object')

In [57]:
begin_inv_df.info

<bound method DataFrame.info of                InventoryId  Store          City  Brand  \
0        1_HARDERSFIELD_58      1  HARDERSFIELD     58
1        1_HARDERSFIELD_60      1  HARDERSFIELD     60
2        1_HARDERSFIELD_62      1  HARDERSFIELD     62
3        1_HARDERSFIELD_63      1  HARDERSFIELD     63
4        1_HARDERSFIELD_72      1  HARDERSFIELD     72
...                    ...    ...           ...    ...
206524  79_BALLYMENA_46985     79     BALLYMENA  46985
206525  79_BALLYMENA_47014     79     BALLYMENA  47014
206526  79_BALLYMENA_47090     79     BALLYMENA  47090
206527  79_BALLYMENA_90011     79     BALLYMENA  90011
206528  79_BALLYMENA_90089     79     BALLYMENA  90089

                         Description   Size  onHand   Price   startDate
0        Gekkeikan Black & Gold Sake  750mL       8   12.99  2016-01-01
1             Canadian Club 1858 VAP  750mL       7   10.99  2016-01-01
2           Herradura Silver Tequila  750mL       6   36.99  2016-01-01
3         Herradura Reposado Tequila  750mL       3   38.99  2016-01-01
4               No. 3 London Dry Gin  750mL       6   34.99  2016-01-01
...                              ...    ...     ...     ...         ...
206524  Rodney Strong Cab Svgn Alexa  750mL      13   22.99  2016-01-01
206525           Juan Gil Jumilla Rd  750mL      13   13.99  2016-01-01
206526    Napa Cellars Cab Svgn Napa  750mL      19   23.99  2016-01-01
206527  Ch Pichon Longville 12 Pauil  750mL      12  144.99  2016-01-01
206528    Ch Lynch Bages 12 Pauillac  750mL      24  119.99  2016-01-01

[206529 rows x 9 columns]>

In [73]:
begin_inv_df.head()

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2016-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2016-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2016-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2016-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2016-01-01

In [58]:
end_inv_df = pd.read_csv(DATA_PATH + "end_inventory.csv")

In [59]:
end_inv_df.shape

(224489, 9)

In [60]:
end_inv_df.columns

Index(['InventoryId', 'Store', 'City', 'Brand', 'Description', 'Size',
       'onHand', 'Price', 'endDate'],
      dtype='object')

In [61]:
end_inv_df.info

<bound method DataFrame.info of               InventoryId  Store          City  Brand  \
0       1_HARDERSFIELD_58      1  HARDERSFIELD     58
1       1_HARDERSFIELD_62      1  HARDERSFIELD     62
2       1_HARDERSFIELD_63      1  HARDERSFIELD     63
3       1_HARDERSFIELD_72      1  HARDERSFIELD     72
4       1_HARDERSFIELD_75      1  HARDERSFIELD     75
...                   ...    ...           ...    ...
224484  81_PEMBROKE_90087     81      PEMBROKE  90087
224485  81_PEMBROKE_90088     81      PEMBROKE  90088
224486  81_PEMBROKE_90089     81      PEMBROKE  90089
224487  81_PEMBROKE_90090     81      PEMBROKE  90090
224488  81_PEMBROKE_90604     81      PEMBROKE  90604

                         Description   Size  onHand   Price     endDate
0        Gekkeikan Black & Gold Sake  750mL      11   12.99  2016-12-31
1           Herradura Silver Tequila  750mL       7   36.99  2016-12-31
2         Herradura Reposado Tequila  750mL       7   38.99  2016-12-31
3               No. 3 London Dry Gin  750mL       4   34.99  2016-12-31
4          Three Olives Tomato Vodka  750mL       7   14.99  2016-12-31
...                              ...    ...     ...     ...         ...
224484  Ch Mouton Rothschild 12 Paui  750mL       3  469.99  2016-12-31
224485  Ch Le Petite Mouton 12 Pauil  750mL       3  134.99  2016-12-31
224486    Ch Lynch Bages 12 Pauillac  750mL       3  119.99  2016-12-31
224487       Ch Lafite Rothschild 12  750mL       3  649.99  2016-12-31
224488        Ch Lynch Bages Pauilac  750mL       2  119.99  2016-12-31

[224489 rows x 9 columns]>

In [62]:
end_inv_df.isna().sum()

InventoryId       0
Store             0
City           1284
Brand             0
Description       0
Size              0
onHand            0
Price             0
endDate           0
dtype: int64

In [71]:
end_inv_df.head()

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2016-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2016-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2016-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2016-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2016-12-31

price_df = pd.read_csv(DATA_PATH + "price.csv")

Price dataset
-  Contains 5543 rows and 10 columns
- Contains the vendor details like: Vendor number, time pr payment, quantity, amount etc

In [64]:
price_df.shape

(5543, 10)

In [65]:
price_df.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='object')

In [66]:
price_df.info

<bound method DataFrame.info of       VendorNumber                   VendorName InvoiceDate  PONumber  \
0              105  ALTAMAR BRANDS LLC           2016-01-04      8124
1             4466  AMERICAN VINTAGE BEVERAGE    2016-01-07      8137
2              388  ATLANTIC IMPORTING COMPANY   2016-01-09      8169
3              480  BACARDI USA INC              2016-01-12      8106
4              516  BANFI PRODUCTS CORP          2016-01-07      8170
...            ...                          ...         ...       ...
5538          9622  WEIN BAUER INC               2017-01-06     13626
5539          9625  WESTERN SPIRITS BEVERAGE CO  2017-01-10     13661
5540          3664  WILLIAM GRANT & SONS INC     2017-01-02     13643
5541          9815  WINE GROUP INC               2017-01-03     13602
5542         90058  ZORVINO VINEYARDS            2017-01-05     13574

          PODate     PayDate  Quantity    Dollars  Freight Approval
0     2015-12-21  2016-02-16         6     214.26     3.47      NaN
1     2015-12-22  2016-02-21        15     140.55     8.57      NaN
2     2015-12-24  2016-02-16         5     106.60     4.61      NaN
3     2015-12-20  2016-02-05     10100  137483.78  2935.20      NaN
4     2015-12-24  2016-02-12      1935   15527.25   429.20      NaN
...          ...         ...       ...        ...      ...      ...
5538  2016-12-21  2017-02-10        90    1563.00     8.60      NaN
5539  2016-12-23  2017-02-18      4617   37300.48   186.50      NaN
5540  2016-12-22  2017-02-04      9848  202815.78   932.95      NaN
5541  2016-12-20  2017-02-08     24747  149007.56   819.54      NaN
5542  2016-12-18  2017-02-12       437    3608.11    16.60      NaN

[5543 rows x 10 columns]>

In [67]:
price_df.isna().sum()

VendorNumber       0
VendorName         0
InvoiceDate        0
PONumber           0
PODate             0
PayDate            0
Quantity           0
Dollars            0
Freight            0
Approval        5169
dtype: int64

In [70]:
price_df.head()

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2016-01-04,8124,2015-12-21,2016-02-16,6,214.26,3.47,NaN
1,4466,AMERICAN VINTAGE BEVERAGE,2016-01-07,8137,2015-12-22,2016-02-21,15,140.55,8.57,NaN
2,388,ATLANTIC IMPORTING COMPANY,2016-01-09,8169,2015-12-24,2016-02-16,5,106.60,4.61,NaN
3,480,BACARDI USA INC,2016-01-12,8106,2015-12-20,2016-02-05,10100,137483.78,2935.20,NaN
4,516,BANFI PRODUCTS CORP,2016-01-07,8170,2015-12-24,2016-02-12,1935,15527.25,429.20,NaN